name: Run Simple Java Program

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java (no Maven)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'none'
          maven-settings: 'none'   # try adding this

      - name: Compile Java files
        run: javac *.java       # Change path if needed

      - name: Run Java program
        run: java HelloWorld    # Change class name if needed
