name: Test Java Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List files
        run: ls -la
        
      - name: Setup Java v3
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      
      - name: Compile Java files
        run: javac *.java || echo "No java files found"
