name: Simple Java Build and Run

on:
  schedule:
    - cron: '0 */6 * * *'   # Every 5 hours
  workflow_dispatch:        # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Required in v3
          java-version: '17'

      - name: List files (debug)
        run: ls -la

      - name: Compile Java files
        run: javac src/*.java

      - name: Run Java program
        run: |
          java -cp src int_1_prog_gh
          java -cp src TestDemo02_gh
